# Generated by Django 5.1 on 2024-09-19 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overview',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
