# Generated by Django 5.1 on 2024-09-21 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_blogpost_cartegory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='cartegory',
            new_name='category',
        ),
    ]
