# Generated by Django 5.1 on 2024-08-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard_profile',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='dashboard_profile',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='dashboard_profile',
            name='image3',
        ),
        migrations.AddField(
            model_name='dashboard_profile',
            name='text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
