# Generated by Django 5.1 on 2024-08-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_image1_dashboard_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard_profile',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
