# Generated by Django 5.1 on 2024-08-29 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_about_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_image',
            name='dashboard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.dashboard'),
        ),
    ]
