# Generated by Django 5.1 on 2024-08-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_about_image_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='a_img1',
            field=models.ImageField(null=True, upload_to='about_images'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='a_img2',
            field=models.ImageField(null=True, upload_to='about_images'),
        ),
        migrations.DeleteModel(
            name='about_image',
        ),
    ]
