# Generated by Django 5.1 on 2024-09-02 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_contact_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='status',
        ),
    ]
