# Generated by Django 5.1 on 2024-09-04 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_contact_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
    ]
