# Generated by Django 5.1 on 2024-09-18 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_contact_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='intro',
        ),
    ]
