# Generated by Django 5.1 on 2024-08-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skils',
            name='composition',
        ),
        migrations.AlterField(
            model_name='duties',
            name='duties',
            field=models.CharField(max_length=400),
        ),
    ]
