# Generated by Django 5.1 on 2024-08-29 14:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_remove_skils_composition_alter_duties_duties'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skils',
            new_name='Skills',
        ),
    ]
