# Generated by Django 5.1 on 2024-08-29 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_rename_skils_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='user',
        ),
        migrations.DeleteModel(
            name='Skill_technologies',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
