# Generated by Django 5.1 on 2024-08-29 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_skills_skill_technologies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='skils',
            new_name='skills',
        ),
    ]
