# Generated by Django 5.1 on 2024-08-29 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_about_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='about_image',
        ),
    ]
