# Generated by Django 5.1 on 2024-09-18 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_delete_about_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='bio',
        ),
    ]
