# Generated by Django 5.1 on 2024-09-18 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_remove_about_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill_Cartegory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='skills',
            name='user',
        ),
        migrations.CreateModel(
            name='Skill_Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proficiency', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=12)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.skill_cartegory')),
            ],
        ),
        migrations.DeleteModel(
            name='Skill_technologies',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
