# Generated by Django 5.1 on 2024-09-18 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0012_remove_workexperience_user_about_address_about_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skill_Set',
            new_name='Skills',
        ),
    ]
