# Generated by Django 5.1 on 2024-09-18 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0013_rename_skill_set_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Myskill',
        ),
    ]
