# Generated by Django 5.1 on 2024-09-19 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0014_rename_skills_myskill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='cerificate',
            new_name='course',
        ),
    ]
