# Generated by Django 5.1 on 2024-09-19 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0016_coursework'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_title', models.CharField(max_length=100)),
                ('achievement_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.education')),
            ],
        ),
    ]
